### ISSUE TITLE
dynamic mode: the scenic code generated is not compilable or have running errors

### ISSUE THREAD

**Issue by zjyhhhher** [javyduck/ChatScene#36]
Hello, I try to use dynamic mode to generate scenic code,but I find the code generated from the descriptions I provide is usually either not compilable or throws errors when running in CARLA.
Even when I use the example description you provided, such as "The ego vehicle is driving straight through a four-way intersection when a pedestrian suddenly crosses from the left front on the zebra crossing and stops as the ego vehicle approaches," or when running the 'dynamic_3.scenic' script in CARLA, I still encounter errors like the following:
```
Command:
scenic safebench/scenario/scenario_data/scenic_data/dynamic_scenario/dynamic_3.scenic --simulate

Output:
Beginning scenario construction...
pygame 2.6.1 (SDL 2.28.4, Python 3.8.20)
Hello from the pygame community. https://www.pygame.org/contribute.html
  Loading cached version of road network...
  Loaded cached network in 1.23 seconds.
  Pruning scenario...
  Pruned scenario in 2.337e-05 seconds.
Scenario constructed in 3.16 seconds.
  Connecting to CARLA on port 2000
  Map loaded in simulator.
Traceback (most recent call last; use -b to show Scenic internals):
  <Scenic internals>
AttributeError: 'Vector' object has no attribute 'heading'
```
Any advice or insights would be greatly appreciated. Thanks in advance!

**Comment by javyduck** [comment]
thanks for raising the issue, I will look into it and let you know

**Comment by silakuzu** [comment]
Hi, I get the same error, could you have a look into that? @javyduck @zjyhhhher

**Comment by javyduck** [comment]
sorry... i was too busy with the coursework in uchicago and research, i will try to squeeze some time in this weekend and fix it, thanks for your patience

**Comment by silakuzu** [comment]
@javyduck hello, I am looking forward to that as I am working with ChatScene for my project. Also, it would be great if you could look at the issue I gave in issue #37 . Please tell me if there is anything I could contribute to help you. Thanks a lot in advance!

**Comment by zjyhhhher** [comment]
> Hi, I get the same error, could you have a look into that? [@javyduck](https://github.com/javyduck) [@zjyhhhher](https://github.com/zjyhhhher)

Hi, I attempted to manually modify the scenic code segment in the database to fix it. It is somewhat time-consuming, but effective🤔
